# This is a basic workflow to help you get started with Actions

name: Liquibase_Docker_GitHub-Hosted

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
   push:
     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    #container:
    #  image: liquibase/liquibase
    steps: 
    # Runs a set of commands using the runners shell 
    - uses: actions/checkout@v2
    - name: Run box version	    
      uses: docker://liquibase/liquibase:latest
    - name: What OS is running
      run: uname -a
    - name: What java version do we have
      run: java -version
    - name: Run Liquibase commands
      run: |
        ls -a
        #liquibase/liquibase --version 
        #liquibase/liquibase --url="jdbc:h2:mem:liquibase" --changeLogFile=./Docker/changeLog.h2.sql --username=liquibase --password=password status --verbose
        #liquibase/liquibase --url="jdbc:h2:mem:liquibase" --changeLogFile=./Docker/changeLog.h2.sql --username=liquibase --password=password updateSQL
        #liquibase/liquibase --url="jdbc:h2:mem:liquibase" --changeLogFile=./Docker/changeLog.h2.sql --username=liquibase --password=password update
