# This is a basic workflow to help you get started with Actions

name: Liquibase_Maven_GitHub-Hosted

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "LBJobCLI and LBJobMaven"
  LBJobMaven:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: RunLiquibaseMavenCommands
        uses: actions/checkout@v2
      - run: | 
          cd SalesManager_h2_version
          mvn -version
          mvn clean package
          git config --global user.email "szandany@liquibase.com"; git config --global user.name "szandany"; git config pull.rebase false; git add .; git commit -m "saving changes"; git push -u origin main
          mvn liquibase:status -Dliquibase.verbose
          mvn liquibase:update
